In [2]:
import numpy as np 
import matplotlib.pyplot as plt

## Input data

In [8]:
n_companies = 8

carbon_emissions = { # in ktCO2e
    'scope_1': np.array([75, 5000, 720, 50, 2500, 25, 30000, 5]),
    'scope_2': np.array([75, 5000, 1030, 350, 4500, 5, 2000, 64]),
    'scope_3': np.array([200, 500, 520, 850, 8000, 50, 200, 146])
}

revenue = np.array([300, 328, 125, 100, 200, 102, 107, 25]) # in $ bn

sector_1 = np.array([1, 0, 1, 1, 0, 1, 0, 0]) # indicator of sector 1
sector_2 = np.array([0, 1, 0, 0, 1, 0, 1, 1]) # indicator of sector 2

In [13]:
vol_array = 0.01 * np.array([12, 21, 23, 19, 20, 33, 43, 19]) # volatility of returns

correl_mat = 0.01 * np.array([
    [100, 0, 0, 0, 0, 0, 0, 0],
    [80, 100, 0, 0, 0, 0, 0, 0],
    [70, 75, 100, 0, 0, 0, 0, 0],
    [60, 65, 80, 100, 0, 0 ,0, 0],
    [70, 50, 70, 85, 100, 0, 0, 0],
    [50, 60, 70, 80, 60, 100, 0, 0],
    [70, 50, 70, 75, 80, 50, 100, 0],
    [70, 75, 80, 85, 75, 80, 70, 100]
])
correl_mat = (correl_mat + correl_mat.T) - np.eye(n_companies)

weights_ref = 0.01 * np.array([20, 17, 17, 13, 11, 10, 6, 6])

print("Correlation matrix:\n", correl_mat)

Correlation matrix:
 [[1.   0.8  0.7  0.6  0.7  0.5  0.7  0.7 ]
 [0.8  1.   0.75 0.65 0.5  0.6  0.5  0.75]
 [0.7  0.75 1.   0.8  0.7  0.7  0.7  0.8 ]
 [0.6  0.65 0.8  1.   0.85 0.8  0.75 0.85]
 [0.7  0.5  0.7  0.85 1.   0.6  0.8  0.75]
 [0.5  0.6  0.7  0.8  0.6  1.   0.5  0.8 ]
 [0.7  0.5  0.7  0.75 0.8  0.5  1.   0.7 ]
 [0.7  0.75 0.8  0.85 0.75 0.8  0.7  1.  ]]


### Question 1

(a) Carbon intensities $\mathcal{CI}_{1+2}$ for scopes $1 + 2$ decribe the company's carbon emissions per $ bn revenue

companies by ktCO2e per $1 mn revenue

CI = CE / Y